=== skipperkongen/cs-thesis-uffe-kostas/kode/schema/knapsack/knapsack_instance.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.diku.dk/robust/autogen/stochknapsack" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.diku.dk/robust/autogen/stochknapsack">

	<!--  DATATYPES -->
	<xsd:simpleType name="distribution">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="discrete" />
			<xsd:enumeration value="normal" />
			<xsd:enumeration value="uniform" />
			<xsd:enumeration value="gamma" />
		</xsd:restriction>
	</xsd:simpleType>


    <xsd:element name="knapsack" type="stochasticKnapsackProblem"></xsd:element>
    
    <xsd:complexType name="stochasticKnapsackProblem">
    	<xsd:sequence>

    		<xsd:element name="items" type="itemList" maxOccurs="1"
    			minOccurs="1">
    		</xsd:element>


    		<xsd:choice maxOccurs="1" minOccurs="1">
    			<xsd:element name="stochasticCapacity"
    				type="distributionType" maxOccurs="1" minOccurs="1">
    			</xsd:element>
    			<xsd:element name="capacity" type="xsd:float" maxOccurs="1" minOccurs="1"></xsd:element>
    		</xsd:choice>
    	</xsd:sequence>
    </xsd:complexType>




    <xsd:complexType name="itemList">
    	<xsd:sequence>
    		<xsd:element name="item" type="itemType" maxOccurs="unbounded" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
    


    <xsd:complexType name="distributionType">
    	<xsd:choice maxOccurs="1" minOccurs="1">
    		<xsd:element name="normal" type="normalDistribution"></xsd:element>
    		<xsd:element name="uniform" type="uniformDistribution"></xsd:element>
    		<xsd:element name="gamma" type="gammaDistribution"></xsd:element>
    		<xsd:element name="polynomial" type="polynomialDistribution"></xsd:element>
    	</xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="normalDistribution">
    	<xsd:attribute name="mean" type="xsd:float" use="required"></xsd:attribute>
    	<xsd:attribute name="variance" type="xsd:float" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="uniformDistribution">
    	<xsd:attribute name="lower" type="xsd:float" use="required"></xsd:attribute>
    	<xsd:attribute name="upper" type="xsd:float" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="gammaDistribution">
    	<xsd:attribute name="shape" type="xsd:float" use="required"></xsd:attribute>
    	<xsd:attribute name="scale" type="xsd:float" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="polynomialDistribution">
    	<xsd:sequence>
    		<xsd:element name="incident" type="incidentType" maxOccurs="unbounded" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="incidentType">
    	<xsd:attribute name="value" type="xsd:float" use="required"></xsd:attribute>
    	<xsd:attribute name="likelyhood" type="xsd:float" use="required"></xsd:attribute>
    </xsd:complexType>


    <xsd:complexType name="itemType">
    	<xsd:sequence maxOccurs="1" minOccurs="1">
    		<xsd:choice maxOccurs="1" minOccurs="1">
    			<xsd:element name="profit" type="xsd:float"></xsd:element>
    			<xsd:element name="stochasticProfit" type="distributionType"></xsd:element>
    		</xsd:choice>
    		<xsd:choice maxOccurs="1" minOccurs="1">
    			<xsd:element name="weight" type="xsd:float"></xsd:element>
    			<xsd:element name="stochasticWeight" type="distributionType"></xsd:element>
    		</xsd:choice>
    	</xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== skipperkongen/cs-thesis-uffe-kostas/kode/xml/kp_instances/stochastic_knapsack_large_values.xml
<?xml version="1.0" encoding="UTF-8"?>
<knapsack xmlns="http://www.diku.dk/robust/autogen/stochknapsack" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.diku.dk/robust/autogen/stochknapsack ../schema/knapsack/knapsack_instance.xsd ">
  <items>
    <item>
      <profit>2.0</profit>
      <stochasticWeight>
      	<normal mean="40" variance="10" />
      </stochasticWeight>
      
    </item>
    <item>
    	<profit>5</profit>
    	<stochasticWeight>
    		<normal mean="70" variance="20" />
    	</stochasticWeight>
    	
    </item>
    <item>
    	<profit>3.0</profit>
    	<stochasticWeight>
    		<normal mean="70" variance="20" ></normal>
    	</stochasticWeight>
    	
    </item>
    <item>
    	<profit>6.0</profit>
    	<stochasticWeight>
    		<normal mean="50" variance="10" />
    	</stochasticWeight>
    	
    </item>
    <item>
    	<profit>3.0</profit>
    	<stochasticWeight>
    		<normal mean="20" variance="2" />
    	</stochasticWeight>
    	
    </item>
    <item>
    	<profit>1.0</profit>
    	<stochasticWeight>
    		<normal mean="40" variance="6" />
    	</stochasticWeight>
    	
    </item>
    <item>
    	<profit>1.0</profit>
    	<stochasticWeight>
    		<normal mean="10" variance="2" />
    	</stochasticWeight>
    	
    </item>
    <item>
    	<profit>2.0</profit>
    	<stochasticWeight>
    		<normal mean="20" variance="1" />
    	</stochasticWeight>
    	
    </item>
    <item>
    	<profit>1.0</profit>
    	<stochasticWeight>
    		<normal mean="30" variance="3" />
    	</stochasticWeight>
    	
    </item>
    <item>
    	<profit>2.0</profit>
    	<stochasticWeight>
    		<normal mean="60" variance="10" />
    	</stochasticWeight>
    	
    </item>
    
  </items>
  <stochasticCapacity>
  	<normal mean="200" variance="40" />
  </stochasticCapacity>
  
</knapsack>

=== skipperkongen/cs-thesis-uffe-kostas/kode/xml/kp_instances/kp_50_items_50_weightSpread_0_capSpread.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<knapsack xmlns="http://www.diku.dk/robust/autogen/stochknapsack" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.diku.dk/robust/autogen/stochknapsack ../../schema/knapsack/knapsack_instance.xsd ">
    <items>
        <item>
            <profit>47.0</profit>
            <stochasticWeight>
                <normal variance="27.5625" mean="21.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>66.0</profit>
            <stochasticWeight>
                <normal variance="33.0625" mean="23.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>58.0</profit>
            <stochasticWeight>
                <normal variance="25.0" mean="20.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>31.0</profit>
            <stochasticWeight>
                <normal variance="33.0625" mean="23.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>66.0</profit>
            <stochasticWeight>
                <normal variance="42.25" mean="26.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>60.0</profit>
            <stochasticWeight>
                <normal variance="33.0625" mean="23.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>40.0</profit>
            <stochasticWeight>
                <normal variance="33.0625" mean="23.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>36.0</profit>
            <stochasticWeight>
                <normal variance="30.25" mean="22.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>53.0</profit>
            <stochasticWeight>
                <normal variance="45.5625" mean="27.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>52.0</profit>
            <stochasticWeight>
                <normal variance="30.25" mean="22.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>39.0</profit>
            <stochasticWeight>
                <normal variance="52.5625" mean="29.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>51.0</profit>
            <stochasticWeight>
                <normal variance="30.25" mean="22.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>61.0</profit>
            <stochasticWeight>
                <normal variance="33.0625" mean="23.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>32.0</profit>
            <stochasticWeight>
                <normal variance="52.5625" mean="29.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>67.0</profit>
            <stochasticWeight>
                <normal variance="42.25" mean="26.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>39.0</profit>
            <stochasticWeight>
                <normal variance="52.5625" mean="29.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>65.0</profit>
            <stochasticWeight>
                <normal variance="36.0" mean="24.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>50.0</profit>
            <stochasticWeight>
                <normal variance="52.5625" mean="29.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>32.0</profit>
            <stochasticWeight>
                <normal variance="52.5625" mean="29.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>56.0</profit>
            <stochasticWeight>
                <normal variance="39.0625" mean="25.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>68.0</profit>
            <stochasticWeight>
                <normal variance="33.0625" mean="23.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>61.0</profit>
            <stochasticWeight>
                <normal variance="49.0" mean="28.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>56.0</profit>
            <stochasticWeight>
                <normal variance="39.0625" mean="25.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>60.0</profit>
            <stochasticWeight>
                <normal variance="27.5625" mean="21.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>73.0</profit>
            <stochasticWeight>
                <normal variance="27.5625" mean="21.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>34.0</profit>
            <stochasticWeight>
                <normal variance="27.5625" mean="21.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>47.0</profit>
            <stochasticWeight>
                <normal variance="45.5625" mean="27.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>35.0</profit>
            <stochasticWeight>
                <normal variance="30.25" mean="22.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>52.0</profit>
            <stochasticWeight>
                <normal variance="36.0" mean="24.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>24.0</profit>
            <stochasticWeight>
                <normal variance="30.25" mean="22.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>69.0</profit>
            <stochasticWeight>
                <normal variance="30.25" mean="22.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>66.0</profit>
            <stochasticWeight>
                <normal variance="42.25" mean="26.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>23.0</profit>
            <stochasticWeight>
                <normal variance="45.5625" mean="27.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>53.0</profit>
            <stochasticWeight>
                <normal variance="39.0625" mean="25.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>52.0</profit>
            <stochasticWeight>
                <normal variance="27.5625" mean="21.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>20.0</profit>
            <stochasticWeight>
                <normal variance="45.5625" mean="27.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>29.0</profit>
            <stochasticWeight>
                <normal variance="42.25" mean="26.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>30.0</profit>
            <stochasticWeight>
                <normal variance="33.0625" mean="23.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>51.0</profit>
            <stochasticWeight>
                <normal variance="33.0625" mean="23.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>21.0</profit>
            <stochasticWeight>
                <normal variance="36.0" mean="24.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>39.0</profit>
            <stochasticWeight>
                <normal variance="36.0" mean="24.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>44.0</profit>
            <stochasticWeight>
                <normal variance="30.25" mean="22.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>57.0</profit>
            <stochasticWeight>
                <normal variance="25.0" mean="20.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>23.0</profit>
            <stochasticWeight>
                <normal variance="42.25" mean="26.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>62.0</profit>
            <stochasticWeight>
                <normal variance="52.5625" mean="29.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>49.0</profit>
            <stochasticWeight>
                <normal variance="25.0" mean="20.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>65.0</profit>
            <stochasticWeight>
                <normal variance="42.25" mean="26.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>19.0</profit>
            <stochasticWeight>
                <normal variance="39.0625" mean="25.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>46.0</profit>
            <stochasticWeight>
                <normal variance="42.25" mean="26.0"/>
            </stochasticWeight>
        </item>
        <item>
            <profit>36.0</profit>
            <stochasticWeight>
                <normal variance="39.0625" mean="25.0"/>
            </stochasticWeight>
        </item>
    </items>
    <stochasticCapacity>
        <normal variance="0.0" mean="1000.0"/>
    </stochasticCapacity>
</knapsack>

=== skipperkongen/cs-thesis-uffe-kostas/kode/xml/kp_instances/stochastic_knapsack.xml
<?xml version="1.0" encoding="UTF-8"?>
<knapsack xmlns="http://www.diku.dk/robust/autogen/stochknapsack" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.diku.dk/robust/autogen/stochknapsack ../../schema/knapsack/knapsack_instance.xsd ">
  <items>
    <item>
      <profit>2.0</profit>
      <stochasticWeight>
      	<normal mean="4.0" variance="1.0" />
      </stochasticWeight>
      
    </item>
    <item>
    	<profit>5.0</profit>
    	<stochasticWeight>
    		<normal mean="7.0" variance="2.0" />
    	</stochasticWeight>
    	
    </item>
    <item>
    	<profit>3.0</profit>
    	<stochasticWeight>
    		<normal mean="7.0" variance="2.0" ></normal>
    	</stochasticWeight>
    	
    </item>
    <item>
    	<profit>6.0</profit>
    	<stochasticWeight>
    		<normal mean="5.0" variance="1.0" />
    	</stochasticWeight>
    	
    </item>
    <item>
    	<profit>3.0</profit>
    	<stochasticWeight>
    		<normal mean="2.0" variance="0.2" />
    	</stochasticWeight>
    	
    </item>
    <item>
    	<profit>1.0</profit>
    	<stochasticWeight>
    		<normal mean="4.0" variance="0.6" />
    	</stochasticWeight>
    	
    </item>
    <item>
    	<profit>1.0</profit>
    	<stochasticWeight>
    		<normal mean="1.0" variance="0.2" />
    	</stochasticWeight>
    	
    </item>
    <item>
    	<profit>2.0</profit>
    	<stochasticWeight>
    		<normal mean="2.0" variance="0.1" />
    	</stochasticWeight>
    	
    </item>
    <item>
    	<profit>1.0</profit>
    	<stochasticWeight>
    		<normal mean="3.0" variance="0.3" />
    	</stochasticWeight>
    	
    </item>
    <item>
    	<profit>2.0</profit>
    	<stochasticWeight>
    		<normal mean="6.0" variance="1.0" />
    	</stochasticWeight>
    	
    </item>
    
  </items>
  <stochasticCapacity>
  	<normal mean="20.0" variance="4.0" />
  </stochasticCapacity>
  
  
  
  
  
  
</knapsack>

=== skipperkongen/cs-thesis-uffe-kostas/kode/xml/kp_instances/non_stochastic_knapsack.xml
<?xml version="1.0" encoding="UTF-8"?>
<knapsack xmlns="http://www.diku.dk/robust/autogen/stochknapsack" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.diku.dk/robust/autogen/stochknapsack ../schema/knapsack/knapsack_instance.xsd ">
  <items>
    <item>
      <profit>2.0</profit>
      <weight>4.0</weight>
    </item>
    <item>
    	<profit>5.0</profit>
    	<weight>7.0</weight>
    </item>
    <item>
    	<profit>3.0</profit>
    	<weight>7.0</weight>
    </item>
    <item>
    	<profit>6.0</profit>
    	<weight>5.0</weight>
    </item>
    <item>
    	<profit>3.0</profit>
    	<weight>2.0</weight>
    </item>
    <item>
    	<profit>1.0</profit>
    	<weight>4.0</weight>
    </item>
    <item>
    	<profit>1.0</profit>
    	<weight>1.0</weight>
    </item>
    
    <item>
    	<profit>2.0</profit>
    	<weight>2.0</weight>
    </item><item>
    	<profit>1.0</profit>
    	<weight>3.0</weight>
    </item>
    <item>
    	<profit>2.0</profit>
    	<weight>6.0</weight>
    </item>
    
  </items>
  <stochasticCapacity>
  	<normal mean="20.0" variance="4.0" />
  </stochasticCapacity>
  
  
  
  
  
  
</knapsack>
