=== skipperkongen/cs-thesis-uffe-kostas/kode/schema/lotsizing/sclsp_solution.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.diku.dk/robust/autogen/sclsp_solution" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.diku.dk/robust/autogen/sclsp_solution">

    <xsd:complexType name="CLSPSolution">
    	<xsd:sequence>
    		<xsd:element name="global_parameters" type="GlobalParameters">
    		</xsd:element>
    		<xsd:element name="on_stock" type="StockTimePeriods" minOccurs="1" maxOccurs="1"></xsd:element>
    		<xsd:element name="being_produced" type="ProductionTimePeriods" minOccurs="1" maxOccurs="1"></xsd:element>
    		<xsd:element name="is_setup" type="IsSetupTimePeriods" minOccurs="1" maxOccurs="1">
    		</xsd:element>
    		<xsd:element name="being_setup" type="BeingSetupTimePeriods" minOccurs="1" maxOccurs="1">
    		</xsd:element>
    		
    	</xsd:sequence>
    </xsd:complexType>
    
    <xsd:element name="solution" type="CLSPSolution"></xsd:element>

    <xsd:complexType name="GlobalParameters">
    	<xsd:attribute name="time_periods" type="xsd:positiveInteger"
    		use="required">
    	</xsd:attribute>
    	<xsd:attribute name="resources" type="xsd:positiveInteger" use="required"></xsd:attribute>
    	<xsd:attribute name="items" type="xsd:positiveInteger" use="required"></xsd:attribute>
    </xsd:complexType>




    <xsd:complexType name="StockTimePeriods">
    	<xsd:sequence minOccurs="1" maxOccurs="unbounded">
    		<xsd:element name="stock_time_period" type="StockTimePeriod"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="StockTimePeriod">
    	<xsd:sequence minOccurs="1" maxOccurs="unbounded">
    		<xsd:element name="item_on_stock" type="ItemOnStock"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="time_period" type="xsd:nonNegativeInteger" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="ItemOnStock">
    	<xsd:attribute name="item_id" type="xsd:nonNegativeInteger" use="required"></xsd:attribute>
    	<xsd:attribute name="amount" type="xsd:nonNegativeInteger" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="ProductionTimePeriods">
    	<xsd:sequence minOccurs="1" maxOccurs="unbounded">
    		<xsd:element name="production_time_period" type="ProductionTimePeriod"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="ProductionTimePeriod">
    	<xsd:sequence minOccurs="1" maxOccurs="unbounded">
    		<xsd:element name="item_production" type="ItemProduction"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="time_period" type="xsd:nonNegativeInteger" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="ItemProduction">
    	<xsd:attribute name="item_id" type="xsd:nonNegativeInteger" use="required"></xsd:attribute>
    	<xsd:attribute name="resource_id" type="xsd:nonNegativeInteger" use="required"></xsd:attribute>
    	<xsd:attribute name="amount" type="xsd:nonNegativeInteger" use="required"></xsd:attribute>
    </xsd:complexType>


    <xsd:complexType name="IsSetupTimePeriods">
    	<xsd:sequence minOccurs="1" maxOccurs="unbounded">
    		<xsd:element name="is_setup_time_period" type="IsSetupTimePeriod"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="IsSetupTimePeriod">
    	<xsd:sequence minOccurs="1" maxOccurs="unbounded">
    		<xsd:element name="resource_is_setup" type="ResourceIsSetup"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="time_period" type="xsd:nonNegativeInteger" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="ResourceIsSetup">
    	<xsd:attribute name="item_id" type="xsd:nonNegativeInteger" use="required"></xsd:attribute>
    	<xsd:attribute name="resource_id" type="xsd:nonNegativeInteger" use="required"></xsd:attribute>
    	<xsd:attribute name="is_setup" type="xsd:boolean" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="BeingSetupTimePeriods">
    	<xsd:sequence minOccurs="1" maxOccurs="unbounded">
    		<xsd:element name="being_setup_time_period" type="BeingSetupTimePeriod"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="BeingSetupTimePeriod">
    	<xsd:sequence minOccurs="1" maxOccurs="unbounded">
    		<xsd:element name="resource_being_setup" type="ResourceBeingSetup"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="time_period" type="xsd:nonNegativeInteger" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="ResourceBeingSetup">
    	<xsd:attribute name="item_id" type="xsd:nonNegativeInteger" use="required"></xsd:attribute>
    	<xsd:attribute name="resource_id" type="xsd:nonNegativeInteger" use="required"></xsd:attribute>
    	<xsd:attribute name="being_setup" type="xsd:boolean" use="required"></xsd:attribute>
    </xsd:complexType>
</xsd:schema>

=== skipperkongen/cs-thesis-uffe-kostas/kode/xml/lsp_solutions/12cap_xtr6_15/solution24.xml
<?xml version="1.0" encoding="UTF-8"?>
<solution 	xmlns="http://www.diku.dk/robust/autogen/sclsp_solution" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.diku.dk/robust/autogen/sclsp_solution ../../schema/lotsizing/sclsp_solution.xsd ">
<global_parameters time_periods="15" resources="1" items="6" />
<on_stock>
  <stock_time_period time_period="1">
  	<item_on_stock item_id="1" amount="503" />
  </stock_time_period>
  <stock_time_period time_period="2">
  	<item_on_stock item_id="1" amount="427" />
  </stock_time_period>
  <stock_time_period time_period="3">
  	<item_on_stock item_id="1" amount="311" />
  </stock_time_period>
  <stock_time_period time_period="4">
  	<item_on_stock item_id="1" amount="209" />
  </stock_time_period>
  <stock_time_period time_period="5">
  	<item_on_stock item_id="1" amount="100" />
  </stock_time_period>
  <stock_time_period time_period="7">
  	<item_on_stock item_id="1" amount="392" />
  </stock_time_period>
  <stock_time_period time_period="8">
  	<item_on_stock item_id="1" amount="294" />
  </stock_time_period>
  <stock_time_period time_period="9">
  	<item_on_stock item_id="1" amount="201" />
  </stock_time_period>
  <stock_time_period time_period="10">
  	<item_on_stock item_id="1" amount="83" />
  </stock_time_period>
  <stock_time_period time_period="12">
  	<item_on_stock item_id="1" amount="325" />
  </stock_time_period>
  <stock_time_period time_period="13">
  	<item_on_stock item_id="1" amount="248" />
  </stock_time_period>
  <stock_time_period time_period="14">
  	<item_on_stock item_id="1" amount="125" />
  </stock_time_period>
  <stock_time_period time_period="0">
  	<item_on_stock item_id="2" amount="281" />
  </stock_time_period>
  <stock_time_period time_period="1">
  	<item_on_stock item_id="2" amount="196" />
  </stock_time_period>
  <stock_time_period time_period="2">
  	<item_on_stock item_id="2" amount="196" />
  </stock_time_period>
  <stock_time_period time_period="3">
  	<item_on_stock item_id="2" amount="101" />
  </stock_time_period>
  <stock_time_period time_period="4">
  	<item_on_stock item_id="2" amount="101" />
  </stock_time_period>
  <stock_time_period time_period="6">
  	<item_on_stock item_id="2" amount="596" />
  </stock_time_period>
  <stock_time_period time_period="7">
  	<item_on_stock item_id="2" amount="497" />
  </stock_time_period>
  <stock_time_period time_period="8">
  	<item_on_stock item_id="2" amount="377" />
  </stock_time_period>
  <stock_time_period time_period="9">
  	<item_on_stock item_id="2" amount="263" />
  </stock_time_period>
  <stock_time_period time_period="10">
  	<item_on_stock item_id="2" amount="169" />
  </stock_time_period>
  <stock_time_period time_period="11">
  	<item_on_stock item_id="2" amount="91" />
  </stock_time_period>
  <stock_time_period time_period="13">
  	<item_on_stock item_id="2" amount="201" />
  </stock_time_period>
  <stock_time_period time_period="14">
  	<item_on_stock item_id="2" amount="97" />
  </stock_time_period>
  <stock_time_period time_period="0">
  	<item_on_stock item_id="3" amount="77" />
  </stock_time_period>
  <stock_time_period time_period="1">
  	<item_on_stock item_id="3" amount="77" />
  </stock_time_period>
  <stock_time_period time_period="3">
  	<item_on_stock item_id="3" amount="500" />
  </stock_time_period>
  <stock_time_period time_period="4">
  	<item_on_stock item_id="3" amount="394" />
  </stock_time_period>
  <stock_time_period time_period="5">
  	<item_on_stock item_id="3" amount="315" />
  </stock_time_period>
  <stock_time_period time_period="6">
  	<item_on_stock item_id="3" amount="192" />
  </stock_time_period>
  <stock_time_period time_period="7">
  	<item_on_stock item_id="3" amount="85" />
  </stock_time_period>
  <stock_time_period time_period="9">
  	<item_on_stock item_id="3" amount="561" />
  </stock_time_period>
  <stock_time_period time_period="10">
  	<item_on_stock item_id="3" amount="456" />
  </stock_time_period>
  <stock_time_period time_period="11">
  	<item_on_stock item_id="3" amount="337" />
  </stock_time_period>
  <stock_time_period time_period="12">
  	<item_on_stock item_id="3" amount="239" />
  </stock_time_period>
  <stock_time_period time_period="13">
  	<item_on_stock item_id="3" amount="114" />
  </stock_time_period>
  <stock_time_period time_period="0">
  	<item_on_stock item_id="4" amount="295" />
  </stock_time_period>
  <stock_time_period time_period="1">
  	<item_on_stock item_id="4" amount="193" />
  </stock_time_period>
  <stock_time_period time_period="2">
  	<item_on_stock item_id="4" amount="92" />
  </stock_time_period>
  <stock_time_period time_period="5">
  	<item_on_stock item_id="4" amount="473" />
  </stock_time_period>
  <stock_time_period time_period="6">
  	<item_on_stock item_id="4" amount="365" />
  </stock_time_period>
  <stock_time_period time_period="7">
  	<item_on_stock item_id="4" amount="270" />
  </stock_time_period>
  <stock_time_period time_period="8">
  	<item_on_stock item_id="4" amount="192" />
  </stock_time_period>
  <stock_time_period time_period="9">
  	<item_on_stock item_id="4" amount="84" />
  </stock_time_period>
  <stock_time_period time_period="11">
  	<item_on_stock item_id="4" amount="425" />
  </stock_time_period>
  <stock_time_period time_period="12">
  	<item_on_stock item_id="4" amount="304" />
  </stock_time_period>
  <stock_time_period time_period="13">
  	<item_on_stock item_id="4" amount="182" />
  </stock_time_period>
  <stock_time_period time_period="14">
  	<item_on_stock item_id="4" amount="80" />
  </stock_time_period>
  <stock_time_period time_period="0">
  	<item_on_stock item_id="5" amount="84" />
  </stock_time_period>
  <stock_time_period time_period="2">
  	<item_on_stock item_id="5" amount="473" />
  </stock_time_period>
  <stock_time_period time_period="3">
  	<item_on_stock item_id="5" amount="386" />
  </stock_time_period>
  <stock_time_period time_period="4">
  	<item_on_stock item_id="5" amount="292" />
  </stock_time_period>
  <stock_time_period time_period="5">
  	<item_on_stock item_id="5" amount="201" />
  </stock_time_period>
  <stock_time_period time_period="6">
  	<item_on_stock item_id="5" amount="111" />
  </stock_time_period>
  <stock_time_period time_period="8">
  	<item_on_stock item_id="5" amount="517" />
  </stock_time_period>
  <stock_time_period time_period="9">
  	<item_on_stock item_id="5" amount="400" />
  </stock_time_period>
  <stock_time_period time_period="10">
  	<item_on_stock item_id="5" amount="295" />
  </stock_time_period>
  <stock_time_period time_period="11">
  	<item_on_stock item_id="5" amount="204" />
  </stock_time_period>
  <stock_time_period time_period="12">
  	<item_on_stock item_id="5" amount="107" />
  </stock_time_period>
  <stock_time_period time_period="14">
  	<item_on_stock item_id="5" amount="103" />
  </stock_time_period>
  <stock_time_period time_period="0">
  	<item_on_stock item_id="6" amount="89" />
  </stock_time_period>
  <stock_time_period time_period="4">
  	<item_on_stock item_id="6" amount="474" />
  </stock_time_period>
  <stock_time_period time_period="5">
  	<item_on_stock item_id="6" amount="388" />
  </stock_time_period>
  <stock_time_period time_period="6">
  	<item_on_stock item_id="6" amount="270" />
  </stock_time_period>
  <stock_time_period time_period="7">
  	<item_on_stock item_id="6" amount="162" />
  </stock_time_period>
  <stock_time_period time_period="8">
  	<item_on_stock item_id="6" amount="79" />
  </stock_time_period>
  <stock_time_period time_period="10">
  	<item_on_stock item_id="6" amount="462" />
  </stock_time_period>
  <stock_time_period time_period="11">
  	<item_on_stock item_id="6" amount="363" />
  </stock_time_period>
  <stock_time_period time_period="12">
  	<item_on_stock item_id="6" amount="271" />
  </stock_time_period>
  <stock_time_period time_period="13">
  	<item_on_stock item_id="6" amount="173" />
  </stock_time_period>
  <stock_time_period time_period="14">
  	<item_on_stock item_id="6" amount="95" />
  </stock_time_period>
</on_stock>
<being_produced>
  <production_time_period time_period="1">
  	<item_production item_id="1" amount="622" resource_id="1" />
  </production_time_period>
  <production_time_period time_period="7">
  	<item_production item_id="1" amount="485" resource_id="1" />
  </production_time_period>
  <production_time_period time_period="12">
  	<item_production item_id="1" amount="447" resource_id="1" />
  </production_time_period>
  <production_time_period time_period="6">
  	<item_production item_id="2" amount="716" resource_id="1" />
  </production_time_period>
  <production_time_period time_period="13">
  	<item_production item_id="2" amount="287" resource_id="1" />
  </production_time_period>
  <production_time_period time_period="3">
  	<item_production item_id="3" amount="624" resource_id="1" />
  </production_time_period>
  <production_time_period time_period="9">
  	<item_production item_id="3" amount="659" resource_id="1" />
  </production_time_period>
  <production_time_period time_period="15">
  	<item_production item_id="3" amount="109" resource_id="1" />
  </production_time_period>
  <production_time_period time_period="5">
  	<item_production item_id="4" amount="591" resource_id="1" />
  </production_time_period>
  <production_time_period time_period="11">
  	<item_production item_id="4" amount="536" resource_id="1" />
  </production_time_period>
  <production_time_period time_period="2">
  	<item_production item_id="5" amount="584" resource_id="1" />
  </production_time_period>
  <production_time_period time_period="8">
  	<item_production item_id="5" amount="623" resource_id="1" />
  </production_time_period>
  <production_time_period time_period="14">
  	<item_production item_id="5" amount="186" resource_id="1" />
  </production_time_period>
  <production_time_period time_period="4">
  	<item_production item_id="6" amount="557" resource_id="1" />
  </production_time_period>
